ALTER TABLE "Fan"
ADD COLUMN "isSubscriber" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "isCreatorAccount" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "Purchase" DROP CONSTRAINT "Purchase_fanId_fkey";
ALTER TABLE "Purchase" ALTER COLUMN "fanId" DROP NOT NULL;
ALTER TABLE "Purchase"
ADD CONSTRAINT "Purchase_fanId_fkey"
FOREIGN KEY ("fanId") REFERENCES "Fan"("id") ON DELETE SET NULL ON UPDATE CASCADE;
