import { BarChart3, ChevronDown, CircleDollarSign, MessageCircleReply, Send, Target, Users } from "lucide-react";
import type { WorkflowAnalyticsView, WorkflowStepAnalyticsView } from "./types";

const currency = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" });

export function WorkflowAnalyticsPanel({ analytics, stepAnalytics }: { analytics: WorkflowAnalyticsView[]; stepAnalytics: WorkflowStepAnalyticsView[] }) {
  return <section className="mt-8"><div className="mb-4"><h2 className="flex items-center gap-2 font-medium text-white"><BarChart3 className="size-4 text-violet-400" />Resultados por workflow y plantilla</h2><p className="mt-1 text-xs text-zinc-500">Vista compacta; abre únicamente la estrategia que quieras analizar.</p></div><div className="grid gap-3">{analytics.map((item) => <details key={item.workflowId} className="group overflow-hidden rounded-2xl border border-white/8 bg-white/[.025] open:border-violet-400/15"><summary className="flex cursor-pointer list-none flex-wrap items-center gap-3 px-4 py-4 transition hover:bg-white/[.025] sm:px-5 [&::-webkit-details-marker]:hidden"><div className="min-w-0 flex-1"><h3 className="truncate font-semibold text-white">{item.workflowName}</h3><p className="mt-1 text-xs text-zinc-600">{item.enrollments} ejecuciones · {item.active} activas · {item.messagesSent} mensajes</p></div><div className="flex items-center gap-4 text-xs"><span className="text-zinc-500"><strong className="font-semibold text-zinc-200">{item.fansReplied}</strong> respuestas</span><span className="text-zinc-500"><strong className="font-semibold text-emerald-300">{item.conversionRate.toFixed(1)}%</strong> conversión</span><span className="hidden text-emerald-300 sm:block">{currency.format(item.attributedRevenueMinor / 100)}</span><ChevronDown className="size-4 text-zinc-600 transition group-open:rotate-180" /></div></summary><div className="border-t border-white/8 p-4 sm:p-5"><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-6"><Metric icon={Users} label="Fans" value={item.uniqueFans} /><Metric icon={Send} label="Mensajes" value={item.messagesSent} /><Metric icon={MessageCircleReply} label="Respondieron" value={item.fansReplied} /><Metric icon={Target} label="Conversiones" value={item.conversions} /><Metric icon={CircleDollarSign} label="Ingreso atribuido" value={currency.format(item.attributedRevenueMinor / 100)} /><Metric icon={BarChart3} label="Tiempo a conversión" value={item.averageConversionMinutes === null ? "—" : formatMinutes(item.averageConversionMinutes)} /></div><p className="mt-4 text-[11px] text-zinc-600">{item.completed} completadas · {item.cancelled} canceladas{item.failed ? ` · ${item.failed} fallidas` : ""}</p><StepAnalyticsTable rows={stepAnalytics.filter((row) => row.workflowId === item.workflowId)} /></div></details>)}{analytics.length === 0 ? <div className="rounded-2xl border border-dashed border-white/10 p-8 text-center text-sm text-zinc-600">Todavía no hay datos de workflows.</div> : null}</div><p className="mt-3 text-[11px] text-zinc-600">Respuestas y conversiones se atribuyen al último mensaje enviado antes de la acción. Los importes solo incluyen pagos confirmados por Fanvue.</p></section>;
}

function StepAnalyticsTable({ rows }: { rows: WorkflowStepAnalyticsView[] }) {
  if (!rows.length) return <p className="mt-5 rounded-xl border border-dashed border-white/8 p-4 text-center text-xs text-zinc-600">Los resultados por mensaje aparecerán después del primer envío.</p>;
  return <div className="mt-5 overflow-hidden rounded-xl border border-white/8"><div className="border-b border-white/8 bg-black/20 px-4 py-3"><p className="text-xs font-medium text-zinc-300">Resultados por mensaje y plantilla</p><p className="mt-1 text-[10px] text-zinc-600">Cada fan cuenta una sola vez por paso, aunque responda varias veces.</p></div><div className="overflow-x-auto"><table className="w-full min-w-190 text-left text-xs"><thead className="bg-white/[.025] text-[10px] uppercase tracking-wide text-zinc-600"><tr><th className="px-4 py-3 font-medium">Paso / plantilla</th><th className="px-3 py-3 font-medium">Envíos</th><th className="px-3 py-3 font-medium">Fans</th><th className="px-3 py-3 font-medium">Respondieron</th><th className="px-3 py-3 font-medium">Tasa</th><th className="px-3 py-3 font-medium">Tiempo medio</th><th className="px-3 py-3 font-medium">Conversiones</th><th className="px-4 py-3 font-medium">Ingreso</th></tr></thead><tbody className="divide-y divide-white/6">{rows.map((row) => <tr key={row.stepId} className="text-zinc-400"><td className="px-4 py-3"><p className="font-medium text-zinc-200">{row.stepName}</p><p className="mt-0.5 text-[10px] text-zinc-600">{row.templateName} · {row.messageKind === "PPV" ? "PPV" : "Mensaje"}</p></td><td className="px-3 py-3">{row.sends}</td><td className="px-3 py-3">{row.recipients}</td><td className="px-3 py-3">{row.responders}</td><td className="px-3 py-3 font-medium text-violet-300">{row.responseRate.toFixed(1)}%</td><td className="px-3 py-3">{row.averageResponseMinutes === null ? "—" : formatMinutes(row.averageResponseMinutes)}</td><td className="px-3 py-3">{row.conversions}</td><td className="px-4 py-3 text-emerald-300">{currency.format(row.attributedRevenueMinor / 100)}</td></tr>)}</tbody></table></div></div>;
}

function Metric({ icon: Icon, label, value }: { icon: typeof Users; label: string; value: string | number }) {
  return <div className="rounded-xl border border-white/6 bg-black/15 p-3"><Icon className="size-4 text-violet-400/70" /><p className="mt-2 text-lg font-semibold text-zinc-200">{value}</p><p className="mt-0.5 text-[10px] uppercase tracking-wide text-zinc-600">{label}</p></div>;
}

function formatMinutes(minutes: number) {
  if (minutes < 60) return `${Math.round(minutes)} min`;
  if (minutes < 1_440) return `${(minutes / 60).toFixed(1)} h`;
  return `${(minutes / 1_440).toFixed(1)} d`;
}
