export const workflowActivityEventTypes = [
  "WORKFLOW_ASSIGNED",
  "WORKFLOW_STARTED",
  "WORKFLOW_CHANGED",
  "WORKFLOW_PAUSED",
  "WORKFLOW_RESUMED",
  "WORKFLOW_CANCELLED",
  "WORKFLOW_MESSAGE_SENT",
  "WORKFLOW_PPV_SENT",
  "WORKFLOW_WAIT_COMPLETED",
  "WORKFLOW_WAIT_STARTED",
  "WORKFLOW_COMPLETED",
  "WORKFLOW_STEP_FAILED",
  "WORKFLOW_RETRY_SCHEDULED",
  "WORKFLOW_FAILED",
  "WORKFLOW_CONDITION_EVALUATED",
  "WORKFLOW_REENTRY_SKIPPED",
  "WORKFLOW_SEND_WINDOW_DEFERRED",
  "WORKFLOW_SEND_LIMIT_DEFERRED",
  "WORKFLOW_PAUSED_BY_REPLY",
  "WORKFLOW_RESUMED_AFTER_SILENCE",
  "WORKFLOW_GOAL_COMPLETED",
  "WORKFLOW_FAN_REPLIED",
] as const;

export function activityRetentionCutoff(now: Date, retentionDays = 90) {
  return new Date(now.getTime() - retentionDays * 24 * 60 * 60 * 1000);
}
