ALTER TABLE "Settings"
ADD COLUMN "sendWindowEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "sendingWindowDays" JSONB NOT NULL DEFAULT '[0,1,2,3,4,5,6]'::jsonb,
ADD COLUMN "sendLimitsEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "maxMessagesPerHour" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN "maxMessagesPerDay" INTEGER NOT NULL DEFAULT 200,
ADD COLUMN "minMinutesBetweenFanMessages" INTEGER NOT NULL DEFAULT 60;
