CREATE TYPE "WorkflowGoalType" AS ENUM ('NONE', 'PAID_SUBSCRIPTION', 'FIRST_PURCHASE', 'ANY_PURCHASE', 'PPV_PURCHASE', 'TIP_RECEIVED', 'SPEND_AMOUNT');

ALTER TABLE "Workflow"
ADD COLUMN "goalType" "WorkflowGoalType" NOT NULL DEFAULT 'NONE',
ADD COLUMN "goalAmountMinor" INTEGER;
